### ISSUE TITLE
Support for Terraform 0.12(Root Level variables error check)

### ISSUE THREAD

**Issue by tommyknows** [juliosueiras/terraform-lsp#10]
Hi,

I just installed this package and am using it with vim / coc.

I am using Terraform 0.12, which does not seem to be supported so far?
For example, somewhere I am using this:
```
namespace = kubernetes_namespace.mynamespace.metadata[0].name
```
and the reported error:
```
 [Terraform Schema] [E] There is no variable named "kubernetes_namespace".
```

Using the "old" terraform 0.11 notation with `"${var.kubernetes_namespace.mynamespace.metadata[0].name"` works fine

**Comment by juliosueiras** [comment]
nah, it does work completion, its just I need to add scope for the root level variables in the error checking phase(since I am doing the terraform check directly instead of terraform validate, since directly allow usage of Range which provide very detail location info)

will work on providing root level variables check within today/tomorrow

**Comment by tommyknows** [comment]
cool, thank you! 😄

**Comment by moritzheiber** [comment]
@juliosueiras Massive thanks for working on this. Let me know if there's anything one can do to help out (testing etc.)

**Comment by wesselvdv** [comment]
Any progress on this?

**Comment by juliosueiras** [comment]
Hi, can you try with 0.0.6?

**Comment by tommyknows** [comment]
Using master - seems to work fine for me. Thank you! 😄

**Comment by juliosueiras** [comment]
No problem, I still need add deep check
